-   id: prettier-eslint
    name: prettier-eslint
    description: 'Run prettier && eslint'
    entry: concurrently "prettier --write --list-different --ignore-unknown" "eslint --cache --fix"
    language: node
    args: []
    require_serial: false
    additional_dependencies: ["concurrently@8.2.2", "prettier@3.1.0", "eslint@7.32.0"]
    minimum_pre_commit_version: '0'
