-   id: prettier-eslint
    name: prettier-eslint
    description: 'Run prettier && eslint'
    entry: prettier --write --list-different --ignore-unknown . && eslint --cache --fix
    language: node
    args: []
    require_serial: false
    additional_dependencies: ["prettier@3.1.0", "eslint@7.32.0"]
    minimum_pre_commit_version: '0'
