-   id: prettier-eslint
    name: prettier-eslint
    description: ''
    entry: prettier-eslint
    language: node
    'types': [files]
    args: ["i"]
    require_serial: false
    additional_dependencies: ["prettier-eslint@8.3.1"]
    minimum_pre_commit_version: '0'
